version: '3.1'

services:

  postgresdb:
    container_name: postgresdb
    image: postgres:11-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_vol:/var/lib/postgresql/data

#  activemq_2:
#    image: webcenter/activemq:latest
#    ports:
#      # mqtt
#      - "1883:1883"
#      # amqp
#      - "5672:5672"
#      # ui
#      - "8161:8161"
#      # stomp
#      - "61613:61613"
#      # ws
#      - "61614:61614"
#      # jms
#      - "61616:61616"   
#    environment:
#      ACTIVEMQ_NAME: amq
#      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: 'True'
#      ACTIVEMQ_ADMIN_LOGIN: admin
#      ACTIVEMQ_ADMIN_PASSWORD: admin
#
#  pgadmin_2:
#      image: dpage/pgadmin4
#      ports:
#        - 8888:80
#      depends_on:
#        - postgresdb
#      environment:
#        PGADMIN_DEFAULT_EMAIL: hudson
#        PGADMIN_DEFAULT_PASSWORD: hudson

volumes:
  postgres_vol:

#TODO: - ./deployment/data/postgres:/var/lib/postgresql/data